In [1]:
import pandas as pd

In [2]:
%pwd

'C:\\Users\\student\\bigdata'

In [3]:
!dir

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 1A2A-9520

 C:\Users\student\bigdata 디렉터리

2020-02-05  오후 04:24    <DIR>          .
2020-02-05  오후 04:24    <DIR>          ..
2020-02-05  오후 04:24    <DIR>          .ipynb_checkpoints
2020-02-05  오후 02:36    <DIR>          examples
2020-02-04  오후 02:33            21,127 numpy실습1.ipynb
2020-02-04  오후 03:27            10,505 numpy실습2.ipynb
2020-02-04  오후 04:49            12,757 pandas실습1.ipynb
2020-02-05  오전 10:55            89,486 pandas실습2.ipynb
2020-02-05  오전 11:40            65,050 pandas실습3.ipynb
2020-02-05  오후 02:35            65,389 pandas실습4.ipynb
2020-02-05  오후 04:24                72 pandas입출력.ipynb
2020-02-04  오전 11:14    <DIR>          test1
2020-02-03  오후 04:24            18,913 데이터타입.ipynb
2020-02-04  오전 10:29             6,893 모듈테스트.ipynb
2020-02-04  오전 11:16             4,731 입출력테스트.ipynb
2020-02-03  오후 02:38            30,810 파이썬기본.ipynb
              11개 파일             325,733 바이트
               5개 디렉터리  183,802,146,816 바이트 남음

In [4]:
%cd examples

C:\Users\student\bigdata\examples

In [5]:
!dir

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 1A2A-9520

 C:\Users\student\bigdata\examples 디렉터리

2020-02-05  오후 02:36    <DIR>          .
2020-02-05  오후 02:36    <DIR>          ..
2017-11-26  오후 01:17                58 ex1.csv
2017-11-26  오후 01:17                42 ex2.csv
2017-11-26  오후 01:17               170 ex3.txt
               3개 파일                 270 바이트
               2개 디렉터리  183,802,212,352 바이트 남음

In [6]:
!type ex1.csv

a,b,c,d,message
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [7]:
%cd ..

C:\Users\student\bigdata

In [8]:
!type examples\ex1.csv

a,b,c,d,message
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [9]:
#pd.read_csv?

In [10]:
df = pd.read_csv('examples/ex1.csv')
df

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [11]:
type(df)

pandas.core.frame.DataFrame

In [12]:
pd.read_table('examples/ex1.csv', sep=',')

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [13]:
!type examples\ex2.csv

1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [14]:
pd.read_csv('examples/ex2.csv', header=None)

   0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

In [15]:
pd.read_csv('examples/ex2.csv')

   1   2   3   4  hello
0  5   6   7   8  world
1  9  10  11  12    foo

In [16]:
pd.read_csv('examples/ex2.csv', names=['a','b','c','d','msg'])

   a   b   c   d    msg
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

In [17]:
f = open('examples/ex3.txt')

In [18]:
list(f)

['            A         B         C\n',
 'aaa -0.264438 -1.026059 -0.619500\n',
 'bbb  0.927272  0.302904 -0.032399\n',
 'ccc -0.264273 -0.386314 -0.217601\n',
 'ddd -0.871858 -0.348382  1.100491\n']