In [ ]:
!pip install pandas

In [1]:
import pandas as pd

In [2]:
%pwd

'd:\\data-science\\3day'

In [3]:
!dir

 D ����̺��� ����: �� ����
 ���� �Ϸ� ��ȣ: A8DA-AEEC

 d:\data-science\3day ���͸�

2026-05-29  ���� 09:06    <DIR>          .
2026-05-29  ���� 09:04    <DIR>          ..
2026-05-27  ���� 05:04    <DIR>          .ipynb_checkpoints
2026-05-29  ���� 09:03           698,599 cancer_PCA_�������_���Խǽ�.ipynb
2026-05-29  ���� 09:06    <DIR>          data
2026-05-27  ���� 05:04    <DIR>          examples
2026-05-29  ���� 02:08            53,971 Pandas_���սǽ�1.ipynb
2026-05-29  ���� 09:03           203,917 Pandas_���սǽ�2.ipynb
2026-05-29  ���� 09:03           591,958 Pandas_���սǽ�3.ipynb
2026-05-29  ���� 09:03           441,184 Pandas_���սǽ�4.ipynb
2026-05-29  ���� 11:14            90,521 pandas�ǽ�2.ipynb
2026-05-27  ���� 02:29               431 pandas�ǽ�2.txt
2026-05-29  ���� 11:14            53,958 pandas�ǽ�3.ipynb
2026-05-29  ���� 02:19            64,765 pandas�ǽ�4.ipynb
2026-05-27  ���� 02:29               806 pandas�ǽ�4.txt
2026-05-27  ���� 02:29               928 pandas�ǽ�4.txt.bak
2026-05-29  ���� 10:25            15,027 pandas�����.ipynb
              12�� ����           2,216,065 ����Ʈ
               5�� ���͸�  1,997,494,722,560 ����Ʈ ����

In [ ]:
%cd examples

In [ ]:
!dir

In [ ]:
!type ex1.csv

In [ ]:
%cd ..

In [ ]:
!type examples\ex1.csv

In [ ]:
#pd.read_csv?

In [4]:
df = pd.read_csv('examples/ex1.csv')
df

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [5]:
type(df)

pandas.DataFrame

In [6]:
pd.read_table('examples/ex1.csv', sep=',')

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [ ]:
!type examples\ex2.csv

In [7]:
pd.read_csv('examples/ex2.csv', header=None)

   0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

In [8]:
pd.read_csv('examples/ex2.csv')

   1   2   3   4  hello
0  5   6   7   8  world
1  9  10  11  12    foo

In [9]:
pd.read_csv('examples/ex2.csv', names=['a','b','c','d','msg'])

   a   b   c   d    msg
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

In [12]:
f = open('examples/ex3.txt')
print(f)

<_io.TextIOWrapper name='examples/ex3.txt' mode='r' encoding='cp949'>

In [11]:
list(f)

['            A         B         C\n',
 'aaa -0.264438 -1.026059 -0.619500\n',
 'bbb  0.927272  0.302904 -0.032399\n',
 'ccc -0.264273 -0.386314 -0.217601\n',
 'ddd -0.871858 -0.348382  1.100491\n']